name: Fetch New Laws

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 UTC every day

jobs:
  fetch-and-update-laws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run fetch_laws script
        run: python fetch_laws.py

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update laws list" -a || echo "No changes to commit"
          git push
